# Generated by Django 4.2.6 on 2024-01-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.bid",
            ),
        ),
    ]
