# Generated by Django 4.2.6 on 2024-01-25 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_offer_alter_listing_price_delete_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="useroffer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
