# Generated by Django 4.2.6 on 2024-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_offer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
