# Generated by Django 4.2.6 on 2024-01-25 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_listing_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
