# Generated by Django 4.2.6 on 2024-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_delete_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
