# Generated by Django 4.2.6 on 2024-01-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_listing_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bid",
        ),
        migrations.AddField(
            model_name="bid",
            name="offer",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to="auctions.bid",
            ),
        ),
    ]
