# Generated by Django 4.2.6 on 2024-01-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_remove_bid_bid_bid_offer_alter_listing_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="offer",
            new_name="bid",
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="auctions.bid",
            ),
        ),
    ]
