# Generated by Django 4.2.6 on 2024-01-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_alter_bid_bid_alter_bid_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Bid",
        ),
    ]
