# Generated by Django 4.2.6 on 2024-01-25 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0021_alter_listing_price_delete_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Listing",
        ),
    ]
