# Generated by Django 4.2.6 on 2024-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_category_listing_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
    ]
