# Generated by Django 4.2.6 on 2024-01-16 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0003_passenger"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Passenger",
            new_name="Passengers",
        ),
    ]
